// NOTES:
//
// BRANDS
//   Brand name must be unique
//   mainColor isn't super important - only used if logoUrl isn't used
//   Shopify domain should be similar to website
//   Shopify token autogenerated in the sign-up process - not relevant for this
//     use dummy values for this for now
//
// USERS
//   Email must be unique
//   Employee data only relevant if user is an employee
//   Employee brand should not be in brands list
//
// POSTS
//   Only normal text is relevant right now for posts, no polls implemented yet
//   Conversation index indicates where in the conversationData list the post
//     conversation can be found (starts at 0)
//   Post types are:
//     0 - undefined, 1 - conversation, 2 - link, 3 - poll, 4 - survey
//     ONLY CONVERSATION SUPPORTED AT THE MOMENT
//
// PERKS
//   Conversation index indicates where in the conversationData list the post
//     conversation can be found (starts at 0)
//   StartDate & EndDate can be null if not a timed perk
//   Perk types are:
//     0 - undefined, 1 - giveaway, 2 - drop, 3 - earnedReward, 4 - productTest,
//     5 - exclusiveProduct
//
// CONVERSATIONS
//   Replies are nested in the parent conversation

var loadData = {
  "brandsData": [
    {
      "name": "BRAND NAME",
      "description": "BRAND DESCRIPTION",
      "logoUrl": "LINK_TO_LOGO_URL",
      "backgroundImageUrl": "LINK_TO_BACKGROUND_IMAGE_URL",
      "website": "LINK_TO_STORE_WEBSITE",
      "mainColor": "COLOR_SCHEME_MAIN_COLOR - HEXCODE #RRGGBB",
      "shopifyToken": "SHOPIFY_TOKEN_AUTOGENERATED",
      "domain": "SHOPIFY_DOMAIN",
      "causes": ["CAUSE_1", "CAUSE_2", "CAUSE_3"],
    },
  ],
  "usersData": [
    {
      "name": "USER_FULL_NAME",
      "email": "USER_EMAIL",
      "description": "USER_BIO_DESCRIPTION",
      "accountPictureUrl": "LINK_TO_ACCOUNT_PICTURE",
      "causes": ["CAUSE_1", "CAUSE_2", "CAUSE_3"],
      "brands": ["BRAND_NAME_1", "BRAND_NAME_2"],
      "employee_data": {
        "brand": "BRAND_NAME",
        "founder": false,
        "owner": false,
        "roles": ["admin"],
        "jobTitle": "JOB TITLE",
      },
    },
  ],
  "postsData": [
    {
      "title": "POST_TITLE",
      "body": "POST_BODY",
      "brand": "BRAND_NAME",
      "creator": "USER_EMAIL",
      "conversationIndex": 0,
    },
  ],
  "perksData": [
    {
      "title": "PERK_TITLE",
      "type": 0,
      "description": "PERK_DESCRIPTION",
      "details": "PERK_DETAILS",
      "productId": "SHOPIFY_ID_FOR_PRODUCT",
      "productName": "SHOPIFY_NAME_FOR_PRODUCT",
      "price": 0.0,
      "imageUrls": ["IMAGE_URL_1", "IMAGE_URL_2"],
      "startDate": DateTime(2022, 1, 1, 0, 0, 0),
      "endDate": DateTime(2022, 2, 1, 0, 0, 0),
      "brand": "BRAND_NAME",
      "creator": "USER_EMAIL",
      "conversationIndex": 0,
    },
  ],
  "conversationsData": [
    {
      "body": "BODY_TEXT",
      "creator": "USER_EMAIL",
      "replies": [
        {
          "body": "BODY_TEXT",
          "creator": "USER_EMAIL",
        },
      ],
    },
  ],
};
