// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:sagelink_communities/app/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (FlutterAppConfig.useEmulator) {
      return DefaultFirebaseOptions.emulator;
    }

    AppEnvironment buildEnv = FlutterAppConfig.environment;

    if (kIsWeb) {
      return buildEnv == AppEnvironment.dev
          ? webDev
          : buildEnv == AppEnvironment.prod
              ? webProd
              : webDemo;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return buildEnv == AppEnvironment.dev
            ? androidDev
            : buildEnv == AppEnvironment.prod
                ? androidProd
                : androidDemo;
      case TargetPlatform.iOS:
        return buildEnv == AppEnvironment.dev
            ? iosDev
            : buildEnv == AppEnvironment.prod
                ? iosProd
                : iosDemo;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // Web options
  static const FirebaseOptions webDemo = FirebaseOptions(
    apiKey: 'AIzaSyCpFceloWPS9naiOYWNCIMQNoWk-iBXYaw',
    appId: '1:851337593328:web:2f04624f53e578d51f5d35',
    messagingSenderId: '851337593328',
    projectId: 'sagelink-community-demo',
    authDomain: 'sagelink-community-demo.firebaseapp.com',
    storageBucket: 'sagelink-community-demo.appspot.com',
    measurementId: 'G-CFP19QCB9E',
  );

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyAM0YIfLpy32yC2jyzgI-jFRu6cILrKcNs',
    appId: '1:365461850788:web:aa2304c666dd7e434f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    authDomain: 'sagelink-community-dev.firebaseapp.com',
    storageBucket: 'sagelink-community-dev.appspot.com',
  );

  static const FirebaseOptions webProd = FirebaseOptions(
    apiKey: 'AIzaSyCuaXewoWsYzw8Fkdb5ldtZ0BcGF1PS02c',
    appId: '1:7241848546:web:088ab6e9cca730ef0670bb',
    messagingSenderId: '7241848546',
    projectId: 'sagelink-community',
    authDomain: 'sagelink-community.firebaseapp.com',
    storageBucket: 'sagelink-community.appspot.com',
    measurementId: 'G-4R6H1YDX3C',
  );

  // Android options
  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyDAY0U7BEMoF_dwuR0bkDj5Svw-0L2Tg3s',
    appId: '1:365461850788:android:81e6363b097840c74f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    storageBucket: 'sagelink-community-dev.appspot.com',
  );

  static const FirebaseOptions androidDemo = FirebaseOptions(
    apiKey: 'AIzaSyAyCC3G1omr2-QSKLvzovCIG2B4GtS-O1o',
    appId: '1:851337593328:android:f7a541ab528b11291f5d35',
    messagingSenderId: '851337593328',
    projectId: 'sagelink-community-demo',
    storageBucket: 'sagelink-community-demo.appspot.com',
  );

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyADJ4RBkoPNtTKyEjyERhCkoObquIxRvRA',
    appId: '1:7241848546:android:1fa8089ca92ae0290670bb',
    messagingSenderId: '7241848546',
    projectId: 'sagelink-community',
    storageBucket: 'sagelink-community.appspot.com',
  );

  // iOS options
  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyC4mVykrxd_9ARflIQTTXXCZf2SVkVNbJ8',
    appId: '1:365461850788:ios:34af71f420a9e6ef4f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    databaseURL: 'https://sagelink-community-dev-default-rtdb.firebaseio.com',
    storageBucket: 'sagelink-community-dev.appspot.com',
    iosClientId:
        '365461850788-422d4veu7o8h24tb3ud709hgbligjdo0.apps.googleusercontent.com',
    iosBundleId: 'com.sagelink.community-app.dev',
  );

  static const FirebaseOptions iosDemo = FirebaseOptions(
    apiKey: 'AIzaSyBgPEfJltYUhqa2tHWNJp3Zl18x-HXj6Oo',
    appId: '1:851337593328:ios:76828cc291cd28751f5d35',
    messagingSenderId: '851337593328',
    projectId: 'sagelink-community-demo',
    storageBucket: 'sagelink-community-demo.appspot.com',
    iosClientId:
        '851337593328-n2bj90en7su5mjidgokpaeomr5imq22g.apps.googleusercontent.com',
    iosBundleId: 'com.sagelink.community-app.demo',
  );

  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyCe6Ou4dwMPys9o2P-Gx3TW6IFo2DbNPqA',
    appId: '1:7241848546:ios:b8eaf2f134611b190670bb',
    messagingSenderId: '7241848546',
    projectId: 'sagelink-community',
    storageBucket: 'sagelink-community.appspot.com',
    iosClientId:
        '7241848546-qqc9oqg0i8f08c7v400ibq7fdmcemtqs.apps.googleusercontent.com',
    iosBundleId: 'com.sagelink.community-app',
  );

  static const FirebaseOptions emulator = FirebaseOptions(
    apiKey: 'AIzaSyC4mVykrxd_9ARflIQTTXXCZf2SVkVNbJ8',
    appId: '1:365461850788:ios:f047368ed58edd154f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    storageBucket: 'sagelink-community-dev.appspot.com',
    iosClientId:
        '365461850788-vajqsmcs6b20u57ok5lbgfbr1tc0qci0.apps.googleusercontent.com',
    iosBundleId: 'com.sagelink.communityApp.dev',
  );
}
