// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:sagelink_communities/app/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    AppEnvironment buildEnv = FlutterAppConfig.environment;

    if (kIsWeb) {
      return buildEnv == AppEnvironment.dev ? webDev : webDemo;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return buildEnv == AppEnvironment.dev ? androidDev : androidDemo;
      case TargetPlatform.iOS:
        return buildEnv == AppEnvironment.dev ? iosDev : iosDemo;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // Web options
  static const FirebaseOptions webDemo = FirebaseOptions(
    apiKey: 'AIzaSyCpFceloWPS9naiOYWNCIMQNoWk-iBXYaw',
    appId: '1:851337593328:web:2f04624f53e578d51f5d35',
    messagingSenderId: '851337593328',
    projectId: 'sagelink-community-demo',
    authDomain: 'sagelink-community-demo.firebaseapp.com',
    storageBucket: 'sagelink-community-demo.appspot.com',
    measurementId: 'G-CFP19QCB9E',
  );

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyAM0YIfLpy32yC2jyzgI-jFRu6cILrKcNs',
    appId: '1:365461850788:web:aa2304c666dd7e434f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    authDomain: 'sagelink-community-dev.firebaseapp.com',
    storageBucket: 'sagelink-community-dev.appspot.com',
  );

  // Android options
  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyDAY0U7BEMoF_dwuR0bkDj5Svw-0L2Tg3s',
    appId: '1:365461850788:android:81e6363b097840c74f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    storageBucket: 'sagelink-community-dev.appspot.com',
  );

  static const FirebaseOptions androidDemo = FirebaseOptions(
    apiKey: 'AIzaSyAyCC3G1omr2-QSKLvzovCIG2B4GtS-O1o',
    appId: '1:851337593328:android:f7a541ab528b11291f5d35',
    messagingSenderId: '851337593328',
    projectId: 'sagelink-community-demo',
    storageBucket: 'sagelink-community-demo.appspot.com',
  );

  // iOS options
  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyC4mVykrxd_9ARflIQTTXXCZf2SVkVNbJ8',
    appId: '1:365461850788:ios:f047368ed58edd154f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    storageBucket: 'sagelink-community-dev.appspot.com',
    iosClientId:
        '365461850788-vajqsmcs6b20u57ok5lbgfbr1tc0qci0.apps.googleusercontent.com',
    iosBundleId: 'com.sagelink.communityApp.dev',
  );

  static const FirebaseOptions iosDemo = FirebaseOptions(
    apiKey: 'AIzaSyBgPEfJltYUhqa2tHWNJp3Zl18x-HXj6Oo',
    appId: '1:851337593328:ios:04f88cb980c57ec81f5d35',
    messagingSenderId: '851337593328',
    projectId: 'sagelink-community-demo',
    storageBucket: 'sagelink-community-demo.appspot.com',
    iosClientId:
        '851337593328-lpldghvrkrkforkp2db3km0o4io7c2mv.apps.googleusercontent.com',
    iosBundleId: 'com.sagelink.communityApp.demo',
  );
}
