// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM0YIfLpy32yC2jyzgI-jFRu6cILrKcNs',
    appId: '1:365461850788:web:aa2304c666dd7e434f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    authDomain: 'sagelink-community-dev.firebaseapp.com',
    storageBucket: 'sagelink-community-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAY0U7BEMoF_dwuR0bkDj5Svw-0L2Tg3s',
    appId: '1:365461850788:android:576490b85818f2644f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    storageBucket: 'sagelink-community-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4mVykrxd_9ARflIQTTXXCZf2SVkVNbJ8',
    appId: '1:365461850788:ios:6ceb4f7e8e4267004f3431',
    messagingSenderId: '365461850788',
    projectId: 'sagelink-community-dev',
    storageBucket: 'sagelink-community-dev.appspot.com',
    iosClientId:
        '365461850788-drvtlauvaqphth93l64bmdqrtfoq84ti.apps.googleusercontent.com',
    iosBundleId: 'com.sagelink.communityApp',
  );
}
